### ISSUE TITLE
"guardians" section of guardian UI dashboard is empty for 1/1 federations

### ISSUE THREAD

**Issue by justinmoon** [fedimint/ui#241] opened 2023-10-24 15:41 UTC
Perhaps we could just hide it?

![image](https://github.com/fedimint/ui/assets/4335621/072829a8-1f9f-4cd0-909a-f92605cc1590)

**Comment by wbobeirne** [comment] 2023-10-24 15:58
Duplicate of #172

**Closed by wbobeirne** 2023-10-24 15:58 UTC
