### ISSUE TITLE
Guardian: Setup UI race condition verifying hashes

### ISSUE THREAD

**Issue by justinmoon** [fedimint/ui#97] opened 2023-07-19 21:24 UTC
If a guardian receives all config hashes from "verify your guardian" screen, doesn't copy and share their config hash, and hits next:

<img width="498" alt="image" src="https://github.com/fedimint/ui/assets/4335621/81793c60-3162-4ba9-932e-463d4f92edc7">

Then they will arrive at this page with no ability to get their config hash and share it with all other guardians. Rest of the guardians can't finish setup.

<img width="480" alt="image" src="https://github.com/fedimint/ui/assets/4335621/9fc8cced-7e1c-401c-9b0f-5b30259b3292">

**Comment by wbobeirne** [comment] 2023-07-19 21:45
Duplicate of #14. Some notes on possible fixes are in there.

**Closed by wbobeirne** 2023-07-19 21:45 UTC
