### ISSUE TITLE
Re-enable single guardian Fedimints

### ISSUE THREAD

**Issue by elsirion** [fedimint/ui#327] opened 2023-11-30 11:22 UTC
We added a special case for single guardian instances. 2 and 3 guardians are still not allowed. Currently (after removing the min requirement on the input field) the UI throws this error when setting number of guardians=1: 

![Screenshot 2023-11-30 at 12-21-27 Guardian UI](https://github.com/fedimint/ui/assets/84478054/2a08a49e-abe6-41dc-835e-0c517944e34c)

**Comment by wbobeirne** [comment] 2023-11-30 15:09
Closing as duplicate of #266

**Closed by wbobeirne** 2023-11-30 15:09 UTC
