### ISSUE TITLE
Race condition when setting up 1-guardian federation

### ISSUE THREAD

**Issue by dpc** [fedimint/ui#188] opened 2023-09-07 16:53 UTC
![Screenshot from 2023-09-07 09-49-09](https://github.com/fedimint/ui/assets/9209/a683dabd-5ebf-43c9-a0c2-01724ae79378)

Refreshing (resubmitting) the page seems to fix it.

**Comment by EthnTuttle** [comment] 2023-09-07 16:53
https://github.com/fedimint/ui/pull/142/files#r1318887381

**Comment by wbobeirne** [comment] 2023-09-07 17:25
Duplicate of #169

**Closed** 2023-09-07 17:25 UTC
